"""
Ticketer Agent - Incident and Change Ticket Management
"""
import os
import json
import random
from datetime import datetime, timezone
from pathlib import Path

from .state import GraphState
from .logger import log_agent_action
from .registry import upsert_incident


def create_incident_node(state: GraphState) -> GraphState:
    """
    Creates a mock Git Incident ticket after drift detection.
    
    Args:
        state: Current graph state
        
    Returns:
        Updated state with incident ticket ID
    """
    severity = state.get("severity", "Unknown")
    entity = state.get("offending_entity", "Unknown")
    incident_id = state.get("incident_id")
    
    # Use existing ID if it matches the format, otherwise generate new
    if incident_id and incident_id.startswith("GIT-INC-"):
        ticket_id = incident_id
    else:
        ticket_id = f"GIT-INC-{random.randint(1000, 9999)}"
    
    msg = f"Opened Incident Ticket {ticket_id} for {entity} ({severity})"
    log_agent_action("ticketer", "Incident Created", msg)
    
    framework = state.get("framework", "Internal")
    control_id = state.get("control_id", "N/A")

    # Initialize the physical evidence file immediately
    evidence_dir = Path("./data/evidence")
    evidence_dir.mkdir(parents=True, exist_ok=True)
    file_path = evidence_dir / f"{ticket_id}.md"
    
    logs = state.get("logs", [])
    initial_evidence = f"""# Incident Report: {ticket_id}
**Status:** OPEN (Awaiting Analysis/Remediation)
**Severity:** {severity}
**Audit Type:** {framework}
**Control Impacted:** {control_id}
**Detected Entity:** {entity}
**Detection Time:** {datetime.now(timezone.utc).isoformat()}

## Summary
The system has detected a potential compliance violation under the **{framework}** framework and initialized this forensic record. 

## Technical Details
The following raw logs were captured during the detection phase.

### Raw Forensic Logs
```json
{json.dumps(logs, indent=2)}
```

---
*This is an automated evidence file generated by Audit Aura.*
"""
    with open(file_path, "w") as f:
        f.write(initial_evidence)
    
    log_agent_action("ticketer", "Evidence Initialized", f"Initial report created at {file_path}")

    execution_entry = {
        "node": "ticketer",
        "message": msg,
        "timestamp": datetime.now(timezone.utc).isoformat(),
        "details": {"ticket_id": ticket_id, "type": "incident"}
    }
    
    # Update incident registry
    upsert_incident(incident_id=ticket_id, incident_ticket_id=ticket_id)
    
    return {
        "incident_ticket_id": ticket_id,
        "execution_log": [execution_entry]
    }


def create_change_node(state: GraphState) -> GraphState:
    """
    Creates a mock Git Change ticket before/during remediation.
    
    Args:
        state: Current graph state
        
    Returns:
        Updated state with change ticket ID
    """
    ticket_id = f"GIT-CHG-{random.randint(1000, 9999)}"
    msg = f"Opened Change Ticket {ticket_id} for remediation tracking."
    log_agent_action("ticketer", "Change Created", msg)
    
    execution_entry = {
        "node": "ticketer",
        "message": msg,
        "timestamp": datetime.now(timezone.utc).isoformat(),
        "details": {"ticket_id": ticket_id, "type": "change"}
    }
    
    incident_id = state.get("incident_id")
    if incident_id:
        upsert_incident(incident_id=incident_id, change_ticket_id=ticket_id)
    
    return {
        "change_ticket_id": ticket_id,
        "execution_log": [execution_entry]
    }


def resolve_incident_node(state: GraphState) -> GraphState:
    """
    Links the Change to Incident and resolves the Incident.
    
    Args:
        state: Current graph state
        
    Returns:
        Updated state with resolution status
    """
    status = state.get("validation_status", "Unknown")
    ticket_id = state.get("incident_ticket_id", "Unknown")
    
    if status == "Success":
        msg = f"Incident {ticket_id} resolved and closed."
    else:
        msg = f"Remediation failed. Incident {ticket_id} remains open."
        
    log_agent_action("ticketer", "Resolution", msg)
    
    execution_entry = {
        "node": "ticketer",
        "message": msg,
        "timestamp": datetime.now(timezone.utc).isoformat(),
        "details": {"status": "resolved" if status == "Success" else "open"}
    }
    
    incident_id = state.get("incident_id")
    if incident_id:
        upsert_incident(
            incident_id=incident_id,
            status="Resolved" if status == "Success" else "In Progress"
        )
    
    return {"execution_log": [execution_entry]}

# Made with Bob
